source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

# Match the CocoaPods version recorded in ios/Podfile.lock. Its transitive
# xcodeproj requirement is intentionally resolved by Gemfile.lock.
gem 'cocoapods', '1.16.2'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
